=== georgwittberger/configdeployer-core/src/main/resources/com/configdeployer/binding/config-profile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://configdeployer.com/profile" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="http://configdeployer.com/profile" version="0.1.3">

    <annotation>
        <documentation>XML schema for the ConfigDeployer profile</documentation>
    </annotation>
    <element name="config-profile">
        <annotation>
            <documentation>Definition of a configuration profile</documentation>
        </annotation>
        <complexType>
            <sequence>
                <element name="properties-files" maxOccurs="1" minOccurs="0">
                    <annotation>
                        <documentation>Group of properties files to operate on</documentation>
                    </annotation>
                    <complexType>
                        <sequence>
                            <element name="properties-file" type="tns:properties-file" maxOccurs="unbounded"
                                minOccurs="1">
                                <annotation>
                                    <documentation>List of properties files to operate on</documentation>
                                </annotation>
                            </element>
                        </sequence>
                    </complexType>
                </element>
                <element name="databases" maxOccurs="1" minOccurs="0">
                    <annotation>
                        <documentation>Group of databases to operate on</documentation>
                    </annotation>
                    <complexType>
                        <sequence>
                            <element name="database" type="tns:database" maxOccurs="unbounded" minOccurs="1">
                                <annotation>
                                    <documentation>List of databases to operate on</documentation>
                                </annotation>
                            </element>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
            <attribute name="name" type="string" use="required">
                <annotation>
                    <documentation>Name of the profile</documentation>
                </annotation>
            </attribute>
            <attribute name="description" type="string" use="optional">
                <annotation>
                    <documentation>Description of the profile</documentation>
                </annotation>
            </attribute>
            <attribute name="version" type="string" use="required">
                <annotation>
                    <documentation>Version of the profile</documentation>
                </annotation>
            </attribute>
        </complexType>
    </element>

    <complexType name="properties-file">
        <sequence>
            <choice maxOccurs="unbounded" minOccurs="0">
                <element name="add" type="tns:properties-add-entry">
                    <annotation>
                        <documentation>Add a properties entry</documentation>
                    </annotation></element>
                <element name="update" type="tns:properties-update-entry">
                    <annotation>
                        <documentation>Update existing properties entries</documentation>
                    </annotation></element>
                <element name="set" type="tns:properties-set-entry">
                    <annotation>
                        <documentation>Add or update a properties entry</documentation>
                    </annotation></element>
                <element name="delete" type="tns:properties-delete-entry">
                    <annotation>
                        <documentation>Delete properties entries</documentation>
                    </annotation></element>
                <element name="rename" type="tns:properties-rename-entry">
                    <annotation>
                        <documentation>Rename key of properties entries</documentation>
                    </annotation></element>
            </choice>
        </sequence>
        <attribute name="location" type="string" use="required">
            <annotation>
                <documentation>Location of the properties file (e.g. /etc/myapp/config.properties)</documentation>
            </annotation>
        </attribute>
        <attribute name="operation" type="tns:properties-file-operation" use="optional">
            <annotation>
                <documentation>Operation to perform for the properties file</documentation>
            </annotation>
        </attribute>
    </complexType>

    <complexType name="properties-add-entry">
        <attribute name="key" type="string" use="required">
            <annotation>
                <documentation>Properties key to add</documentation>
            </annotation>
        </attribute>
        <attribute name="value" type="string" use="optional">
            <annotation>
                <documentation>Value to set for the properties key</documentation>
            </annotation>
        </attribute>
        <attribute name="comment" type="string" use="optional">
            <annotation>
                <documentation>Comment for the properties entry</documentation>
            </annotation>
        </attribute>
    </complexType>

    <complexType name="properties-update-entry">
        <sequence>
            <element name="condition" maxOccurs="unbounded" minOccurs="0" type="tns:properties-entry-condition">
                <annotation>
                    <documentation>List of conditions that must be satisfied to update an entry</documentation>
                </annotation>
            </element>
        </sequence>
        <attribute name="key" type="string" use="optional">
            <annotation>
                <documentation>Properties key to update</documentation>
            </annotation>
        </attribute>
        <attribute name="key-pattern" type="string" use="optional">
            <annotation>
                <documentation>Regular expression defining all keys to update</documentation>
            </annotation></attribute>
        <attribute name="value" type="string" use="optional">
            <annotation>
                <documentation>Value to set for the properties key</documentation>
            </annotation>
        </attribute>
        <attribute name="comment" type="string" use="optional">
            <annotation>
                <documentation>Comment for the properties entry</documentation>
            </annotation>
        </attribute>
    </complexType>

    <complexType name="properties-set-entry">
        <sequence>
            <element name="condition" maxOccurs="unbounded" minOccurs="0" type="tns:properties-entry-condition">
                <annotation>
                    <documentation>List of conditions that must be satisfied to update an entry</documentation>
                </annotation>
            </element>
        </sequence>
        <attribute name="key" type="string" use="required">
            <annotation>
                <documentation>Properties key to add or update</documentation>
            </annotation>
        </attribute>
        <attribute name="value" type="string" use="optional">
            <annotation>
                <documentation>Value to set for the properties key</documentation>
            </annotation>
        </attribute>
        <attribute name="comment" type="string" use="optional">
            <annotation>
                <documentation>Comment for the properties entry</documentation>
            </annotation>
        </attribute>
    </complexType>

    <complexType name="properties-delete-entry">
        <sequence>
            <element name="condition" maxOccurs="unbounded" minOccurs="0" type="tns:properties-entry-condition">
                <annotation>
                    <documentation>List of conditions that must be satisfied to delete the entry</documentation>
                </annotation>
            </element>
        </sequence>
        <attribute name="key" type="string" use="optional">
            <annotation>
                <documentation>Properties key to delete</documentation>
            </annotation>
        </attribute>
        <attribute name="key-pattern" type="string" use="optional">
            <annotation>
                <documentation>Regular expression defining all keys to delete</documentation>
            </annotation></attribute>
    </complexType>

    <complexType name="properties-rename-entry">
        <sequence>
            <element name="condition" maxOccurs="unbounded" minOccurs="0" type="tns:properties-entry-condition">
                <annotation>
                    <documentation>List of conditions that must be satisfied to rename an entry</documentation>
                </annotation>
            </element>
        </sequence>
        <attribute name="key" type="string" use="optional">
            <annotation>
                <documentation>Properties key to rename</documentation>
            </annotation>
        </attribute>
        <attribute name="key-pattern" type="string" use="optional">
            <annotation>
                <documentation>Regular expression defining all keys to rename</documentation>
            </annotation></attribute>
        <attribute name="value" type="string" use="required">
            <annotation>
                <documentation>New properties key (may contain backrefs when using key-pattern)</documentation>
            </annotation>
        </attribute>
        <attribute name="comment" type="string" use="optional">
            <annotation>
                <documentation>Comment for the properties entry</documentation>
            </annotation>
        </attribute>
    </complexType>

    <complexType name="properties-entry-condition">
        <attribute name="value-equals" type="string" use="optional">
            <annotation>
                <documentation>Value of the current properties entry must equal this string (case-sensitive)
                </documentation>
            </annotation>
        </attribute>
        <attribute name="value-contains" type="string" use="optional">
            <annotation>
                <documentation>Value of the current properties entry must contain this string (case-sensitive)
                </documentation>
            </annotation>
        </attribute>
        <attribute name="value-matches" type="string" use="optional">
            <annotation>
                <documentation>Value of the current properties entry must match this regular expression</documentation>
            </annotation>
        </attribute>
        <attribute name="value-not-equals" type="string" use="optional">
            <annotation>
                <documentation>Value of the current properties entry must not equal this string (case-sensitive)
                </documentation>
            </annotation>
        </attribute>
        <attribute name="value-not-contains" type="string" use="optional">
            <annotation>
                <documentation>Value of the current properties entry must not contain this string (case-sensitive)
                </documentation>
            </annotation>
        </attribute>
        <attribute name="value-not-matches" type="string" use="optional">
            <annotation>
                <documentation>Value of the current properties entry must not match this regular expression
                </documentation>
            </annotation>
        </attribute>
    </complexType>

    <simpleType name="properties-file-operation">
        <annotation>
            <documentation>Operation to perform for the properties file:
                CREATE = Create or modify the file
                DELETE = Remove the file entirely
            </documentation>
        </annotation>
        <restriction base="string">
            <enumeration value="CREATE"></enumeration>
            <enumeration value="DELETE"></enumeration>
        </restriction>
    </simpleType>

    <complexType name="database">
        <sequence>
            <element name="entry" type="tns:database-entry" maxOccurs="unbounded" minOccurs="1">
                <annotation>
                    <documentation>List of modifications to perform on the database</documentation>
                </annotation>
            </element>
        </sequence>
        <attribute name="driver-class" type="string" use="required">
            <annotation>
                <documentation>Full-qualified Java class name of the database driver</documentation>
            </annotation>
        </attribute>
        <attribute name="jdbc-url" type="string" use="required">
            <annotation>
                <documentation>JDBC connection URL</documentation>
            </annotation>
        </attribute>
        <attribute name="username" type="string" use="optional">
            <annotation>
                <documentation>Username for authentication</documentation>
            </annotation>
        </attribute>
        <attribute name="password" type="string" use="optional">
            <annotation>
                <documentation>Password for authentication</documentation>
            </annotation>
        </attribute>
    </complexType>


    <complexType name="database-entry">
        <sequence>
            <element name="column-value" type="tns:database-entry-column-value" maxOccurs="unbounded" minOccurs="0">
                <annotation>
                    <documentation>Values to set in the columns of the table</documentation>
                </annotation>
            </element>
        </sequence>
        <attribute name="operation" type="tns:database-entry-operation" use="required">
            <annotation>
                <documentation>Type of operation to perform on the rows of the table</documentation>
            </annotation>
        </attribute>
        <attribute name="table-name" type="string" use="required">
            <annotation>
                <documentation>Name of the table to operate on</documentation>
            </annotation>
        </attribute>
        <attribute name="condition" type="string" use="optional">
            <annotation>
                <documentation>SQL condition selecting the rows to update or delete</documentation>
            </annotation>
        </attribute>
    </complexType>

    <simpleType name="database-entry-operation">
        <restriction base="string">
            <enumeration value="ADD"></enumeration>
            <enumeration value="UPDATE"></enumeration>
            <enumeration value="DELETE"></enumeration>
        </restriction>
    </simpleType>

    <complexType name="database-entry-column-value">
        <attribute name="name" type="string" use="required">
            <annotation>
                <documentation>Column name</documentation>
            </annotation>
        </attribute>
        <attribute name="type" type="tns:database-entry-column-type" use="required">
            <annotation>
                <documentation>Data type of the column</documentation>
            </annotation>
        </attribute>
        <attribute name="value" type="string" use="optional">
            <annotation>
                <documentation>Value to set in the column</documentation>
            </annotation>
        </attribute>
    </complexType>

    <simpleType name="database-entry-column-type">
        <restriction base="string">
            <enumeration value="BIGINT"></enumeration>
            <enumeration value="BOOLEAN"></enumeration>
            <enumeration value="CLOB"></enumeration>
            <enumeration value="DATE"></enumeration>
            <enumeration value="DOUBLE"></enumeration>
            <enumeration value="FLOAT"></enumeration>
            <enumeration value="INTEGER"></enumeration>
            <enumeration value="NUMERIC"></enumeration>
            <enumeration value="SMALLINT"></enumeration>
            <enumeration value="TIME"></enumeration>
            <enumeration value="TIMESTAMP"></enumeration>
            <enumeration value="TINYINT"></enumeration>
            <enumeration value="VARCHAR"></enumeration>
        </restriction>
    </simpleType>
</schema>

=== georgwittberger/configdeployer-core/src/main/resources/com/configdeployer/binding/config-profile-example.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-profile name="Example Profile" description="Optional description of the profile" version="1.0"
    xmlns="http://configdeployer.com/profile" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://configdeployer.com/profile config-profile.xsd ">
    <properties-file location="${env:BASEDIR}/basic.properties">
        <add key="added.key" value="Entry which is only added if it does not exist" />
        <update key="updated.key" value="Value which is only set if key already exists" />
        <set key="set.key" value="Value which is always set" />
        <delete key="deleted.key" />
        <rename key="old.key" new-key="new.key" />
    </properties-file>
    <properties-file location="${sys:user.home}/conditional.properties">
        <set key="conditional.string" value="Value which is only set if current value is 'foo'">
            <condition value-equals="foo" />
        </set>
        <update key="conditional.regex" value="Value which is only set of current value is at least one digit">
            <condition value-matches="\d+" />
        </update>
    </properties-file>
    <properties-file location="${env:USERPROFILE}/comments.properties">
        <add key="commented.key" value="Added entry with comment" comment="This is an entry with comment" />
    </properties-file>
    <properties-file location="${sys:user.home}/keymatching.properties">
        <update key-pattern="number\.\d+\.key" value="Value which is set for all keys matching the pattern" />
    </properties-file>
    <database driver-class="oracle.jdbc.OracleDriver" jdbc-url="jdbc:oracle:thin:@myhost:1521:orcl"
        username="${env:DBUSER}" password="${env:DBPWD}">
        <add table="employees">
            <set column="firstname" type="VARCHAR" value="Emily" />
            <set column="lastname" type="VARCHAR" value="Blunt" />
        </add>
        <update table="movies" condition="title = 'Edge of Tomorrow'">
            <set column="genre" type="VARCHAR" value="Sci-Fi" />
        </update>
        <delete table="movies" condition="year &lt; 1970" />
    </database>
</config-profile>
